export const FOCUS_OPTIONS = [
  { title: "Accessibility Design", value: "accessibility-design" },
  { title: "AR/VR Design", value: "ar-vr-design" },
  { title: "Brand Identity", value: "brand-identity" },
  { title: "Content Strategy", value: "content-strategy" },
  { title: "Design Ops", value: "design-ops" },
  { title: "Information Architecture", value: "information-architecture" },
  { title: "Interaction Design", value: "interaction-design" },
  { title: "Product Design", value: "product-design" },
  { title: "Product Strategy", value: "product-strategy" },
  { title: "Product Management", value: "product-management" },
  { title: "Service Design", value: "service-design" },
  { title: "UI Design", value: "ui-design" },
  { title: "Usability Evaluation", value: "usability-evaluation" },
  { title: "User Research", value: "user-research" },
  { title: "UX Leadership", value: "ux-leadership" },
] as const;

export const ISLAND_OPTIONS = [
  { title: "O\u02BBahu", value: "oahu" },
  { title: "Hawai\u02BBi (Big Island)", value: "hawaii" },
  { title: "Maui", value: "maui" },
  { title: "Kaua\u02BBi", value: "kauai" },
  { title: "Moloka\u02BBi", value: "molokai" },
  { title: "L\u0101na\u02BBi", value: "lanai" },
  { title: "Mainland / International", value: "mainland-international" },
] as const;

export const ISLAND_CITIES: Record<string, readonly { title: string; value: string }[]> = {
  oahu: [
    { title: "Honolulu", value: "Honolulu" },
    { title: "Waikīkī", value: "Waikīkī" },
    { title: "Kailua", value: "Kailua" },
    { title: "Kāneʻohe", value: "Kāneʻohe" },
    { title: "Pearl City", value: "Pearl City" },
    { title: "ʻAiea", value: "ʻAiea" },
    { title: "Kapolei", value: "Kapolei" },
    { title: "ʻEwa Beach", value: "ʻEwa Beach" },
    { title: "Mililani", value: "Mililani" },
    { title: "Wahiawā", value: "Wahiawā" },
    { title: "Waipahu", value: "Waipahu" },
    { title: "Haleʻiwa", value: "Haleʻiwa" },
  ],
  hawaii: [
    { title: "Hilo", value: "Hilo" },
    { title: "Kailua-Kona", value: "Kailua-Kona" },
    { title: "Waimea (Kamuela)", value: "Waimea (Kamuela)" },
    { title: "Waikōloa", value: "Waikōloa" },
    { title: "Captain Cook", value: "Captain Cook" },
    { title: "Pāhoa", value: "Pāhoa" },
    { title: "Keaʻau", value: "Keaʻau" },
    { title: "Volcano", value: "Volcano" },
  ],
  maui: [
    { title: "Kahului", value: "Kahului" },
    { title: "Wailuku", value: "Wailuku" },
    { title: "Kīhei", value: "Kīhei" },
    { title: "Lahaina", value: "Lahaina" },
    { title: "Pāʻia", value: "Pāʻia" },
    { title: "Haʻikū", value: "Haʻikū" },
    { title: "Makawao", value: "Makawao" },
    { title: "Pukalani", value: "Pukalani" },
  ],
  kauai: [
    { title: "Līhuʻe", value: "Līhuʻe" },
    { title: "Kapaʻa", value: "Kapaʻa" },
    { title: "Pōʻipū", value: "Pōʻipū" },
    { title: "Princeville", value: "Princeville" },
    { title: "Kōloa", value: "Kōloa" },
    { title: "Hanalei", value: "Hanalei" },
    { title: "Waimea", value: "Waimea" },
    { title: "Kalāheo", value: "Kalāheo" },
  ],
  molokai: [
    { title: "Kaunakakai", value: "Kaunakakai" },
    { title: "Maunaloa", value: "Maunaloa" },
  ],
  lanai: [
    { title: "Lānaʻi City", value: "Lānaʻi City" },
  ],
};

export const EXPERIENCE_LEVEL_OPTIONS = [
  { title: "Student or Transitioning", value: "student-transitioning" },
  { title: "< 1 year", value: "less-than-1-year" },
  { title: "1-2 years", value: "1-2-years" },
  { title: "3-4 years", value: "3-4-years" },
  { title: "5-9 years", value: "5-9-years" },
  { title: "10-19 years", value: "10-19-years" },
  { title: "20+ years", value: "20-plus-years" },
] as const;

export const INDUSTRY_OPTIONS = [
  { title: "Technology", value: "technology" },
  { title: "Healthcare", value: "healthcare" },
  { title: "Finance", value: "finance" },
  { title: "E-commerce", value: "ecommerce" },
  { title: "Education", value: "education" },
  { title: "Government", value: "government" },
  { title: "Non-profit", value: "nonprofit" },
  { title: "Entertainment", value: "entertainment" },
  { title: "Travel & Hospitality", value: "travel-hospitality" },
  { title: "Real Estate", value: "real-estate" },
  { title: "Food & Beverage", value: "food-beverage" },
  { title: "Retail", value: "retail" },
  { title: "Automotive", value: "automotive" },
  { title: "Energy", value: "energy" },
  { title: "Agriculture", value: "agriculture" },
  { title: "Other", value: "other" },
] as const;
